#raspberry pins
LEFT_SENSOR_TRIGGER_PIN = 17
LEFT_SENSOR_ECHO_PIN = 27
RIGHT_SENSOR_TRIGGER_PIN = 17
RIGHT_SENSOR_ECHO_PIN = 27
FRONT_SENSOR_TRIGGER_PIN = 17
FRONT_SENSOR_ECHO_PIN = 27
LIGHT_PIN = 22

DC_MOTOR_PIN = 23

#thresholds
PROXIMITY_THRESHOLD = 20 # cm